server:
  port: 9999

hibernate:
  dialect: org.hibernate.dialect.H2Dialect

springdoc:
  api-docs:
    path: /api-docs

dicebear:
  url: https://api.dicebear.com/9.x
  style: /lorelei
  format: /svg
  seed: ?seed={seed}

api:
  profile:
    picture:
      format: svg
      mime: image/svg+xml


spring:

  application:
    name: FakePersonGenerator

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  datasource:
    url: jdbc:h2:mem:dev
    username: dev
    password: 123
    platform: h2

  h2:
    console:
      enabled: true

  sql:
    init:
      mode: always
      data-locations: optional:classpath:sql/data/regions.sql, optional:classpath:sql/data/names.sql, optional:classpath:sql/data/lastnames.sql
      schema-locations: optional:classpath*:sql/schema/*
